<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '19',
    'typeid' => '0',
    'title' => '芋圆九号',
    'style' => '',
    'thumb' => 'http://localhost/dhmm/uploadfile/2016/1014/20161014014551654.jpg',
    'keywords' => '九号',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=19&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1476423855',
    'updatetime' => '1476423951',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '19',
    'typeid' => '0',
    'title' => '芋圆九号',
    'style' => '',
    'thumb' => 'http://localhost/dhmm/uploadfile/2016/1014/20161014014554900.jpg',
    'keywords' => '九号',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=19&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1476423855',
    'updatetime' => '1476423954',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>