<?php
return array (
  10 => 
  array (
    'id' => '10',
    'catid' => '19',
    'typeid' => '0',
    'title' => '芋圆一号',
    'style' => '',
    'thumb' => 'http://www.dhmm.com/uploadfile/2016/1121/20161121032958818.png',
    'keywords' => '芋圆一号',
    'description' => '芋圆一号',
    'posids' => '0',
    'url' => 'http://www.dhmm.com/index.php?m=content&c=index&a=show&catid=19&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1479713376',
    'updatetime' => '1479713417',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '19',
    'typeid' => '0',
    'title' => '芋圆一号',
    'style' => '',
    'thumb' => 'http://www.dhmm.com/uploadfile/2016/1121/20161121033039301.png',
    'keywords' => '芋圆一号',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.dhmm.com/index.php?m=content&c=index&a=show&catid=19&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1479713421',
    'updatetime' => '1479713455',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '20',
    'typeid' => '0',
    'title' => '仙草九号',
    'style' => '',
    'thumb' => 'http://localhost/dhmm/uploadfile/2016/1014/20161014014840337.jpg',
    'keywords' => '九号 仙草',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=20&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1476424087',
    'updatetime' => '1476424120',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '21',
    'typeid' => '0',
    'title' => '传世豆花1号',
    'style' => '',
    'thumb' => 'W020160202100774089606.jpg',
    'keywords' => '豆花',
    'description' => '3、防止骨质疏松　　现代医学证明，豆腐脑中钙的含量非常高，通常情况下两小块豆腐就可以满足一个人一整天钙的需要，而豆腐脑中的钙含量更   ',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=21&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1476424609',
    'updatetime' => '1476424622',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '22',
    'typeid' => '0',
    'title' => '妈妈好饮',
    'style' => '',
    'thumb' => 'W020160202100774089606.jpg',
    'keywords' => '妈妈',
    'description' => '3、防止骨质疏松　　现代医学证明，豆腐脑中钙的含量非常高，通常情况下两小块豆腐就可以满足一个人一整天钙的需要，而豆腐脑中的钙含量更   ',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=22&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1476424634',
    'updatetime' => '1476424647',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '19',
    'typeid' => '0',
    'title' => '芋圆一号',
    'style' => '',
    'thumb' => 'http://www.dhmm.com/uploadfile/2016/1121/20161121033120676.png',
    'keywords' => '芋圆一号',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.dhmm.com/index.php?m=content&c=index&a=show&catid=19&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1479713460',
    'updatetime' => '1479713517',
    'hitsid' => 'c-1-12',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>