<?php
return array (
  8 => 
  array (
    'id' => '8',
    'catid' => '45',
    'typeid' => '0',
    'title' => '未来5年我国将制订完善1000项食品标准',
    'style' => '',
    'thumb' => '',
    'keywords' => '我国 标准 食品',
    'description' => '未来5年我国将制订完善1000项食品标准',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=45&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1478592778',
    'updatetime' => '1478750258',
    'hitsid' => 'c-1-8',
    'views' => '5',
    'yesterdayviews' => '0',
    'dayviews' => '5',
    'weekviews' => '5',
    'monthviews' => '5',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '45',
    'typeid' => '0',
    'title' => '豆花妈妈被《大武汉》评为武汉台式甜品代表',
    'style' => '',
    'thumb' => '',
    'keywords' => '武汉 豆花 甜品',
    'description' => '豆花妈妈被《大武汉》评为武汉台式甜品代表',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=45&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1478592812',
    'updatetime' => '1478681383',
    'hitsid' => 'c-1-9',
    'views' => '4',
    'yesterdayviews' => '1',
    'dayviews' => '3',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '45',
    'typeid' => '0',
    'title' => '热烈祝贺武汉豆花妈妈食品有限公司网站正式开通！',
    'style' => '',
    'thumb' => '',
    'keywords' => '豆花 武汉 妈妈',
    'description' => '订单的',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=45&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1478592649',
    'updatetime' => '1478592727',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '45',
    'typeid' => '0',
    'title' => '这样的手打豆花真的是很有味',
    'style' => '',
    'thumb' => '',
    'keywords' => '豆花',
    'description' => '订单的',
    'posids' => '0',
    'url' => 'http://localhost/dhmm/index.php?m=content&c=index&a=show&catid=45&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1478592758',
    'updatetime' => '1478592767',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>